version: '3.8'
services:
  # MySQL Database
  mysql:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # C# API (Backend)
  todo-api:
    build:
      context: ./todo-api/api
      dockerfile: Dockerfile
    ports:
      - "5194:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=tododb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always
    command: ["dotnet", "todo-api.dll"]

  # React Frontend
  todo-web:
    build:
      context: ./todo-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Serving static React build via Nginx on port 80
    environment:
      - REACT_APP_API_URL=http://localhost:5194/api/todo
      - NODE_ENV=production
    depends_on:
      - todo-api
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
